name: Test pull request

on:
  pull_request:
    branches:
      - master

jobs:
  test_pull_request:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Initialize Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email ""
      - name: Lint
        run: npm run lint
